[platformio]
default_envs = esp32s3_wrist

; --------------------------------------
; NODE 1: WRIST DISPLAY (ESP32-S3 N8R8)
; --------------------------------------
[env:esp32s3_wrist]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<wrist/>
lib_deps =
  moononournation/GFX Library for Arduino @ 1.4.0

; --------------------------------------
; NODE 2: KNUCKLE CAMERA (ESP32-CAM)
; --------------------------------------
[env:esp32cam_knuckle]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
build_src_filter = +<knuckle/>

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue